config/routes.rb
Rails.application.routes.draw do
  root "pages#index"

  resources :pages
  resources :codes
  get 'search', to: 'search#search'

  get "/privacypolicy" => "pages#indexToS"
  get "/termsofservice" => "pages#indexShow"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/code.rb
require 'elasticsearch/model'
class Code < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  # index_name Rails.application.class.parent_name.underscore
  # document_type self.name.downcase

  serialize :includes
  serialize :inclusionTerm
  serialize :excludes1
  serialize :excludes2
  # belongs_to :parent, :class_name => "Code", :join_table => :relationships, foreign_key: :child_id
  # has_many :children, :class_name => "Code", table_name: "relationships", foreign_key: :parent_id
  # has_one :parent, :class_name => "Code", :join_table => :relationships, foreign_key: :child_id
  # belongs_to :parent, inverse_of: :children
  # belongs_to :parent, :class_name => "Code", :join_table => :relationships, foreign_key: :child_id
  #for top level parent create excliusion because it wont have a parent


  # def self.search(query)
  #   __elasticsearch__.search(
  #     {
  #       size: 1000,
  #       query: {
  #         multi_match: {
  #           query: query,
  #           fields: ['code_id^10', 'desc']
  #         }
  #       }
  #     }
  #   )
  # end

  def children
    Code.where(parent_id: self.code_id)
  end

  def parent
    Code.find_by(code_id: self.parent_id)
  end
end

app/models/exclusion.rb
class Exclusion < ApplicationRecord
  belongs_to :code
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :code
end

app/models/inclusion_term.rb
class InclusionTerm < ApplicationRecord
  belongs_to :code
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/recent.rb
class Recent < ApplicationRecord
  belongs_to :user
  belongs_to :code
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
def index
  @codes = Code.all
end

def show
  @code = Code.find params[:id]
end


end

# private
#   def codes_params
#     params.require(:code).permit :title, :text
#   end
#
# end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  def indexShow
    @pages = Page.all
  end

  def indexToS
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:index)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
  if params[:q].nil?
    @codes = []
  else
    @codes = Code.search params[:q]
  end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/codes/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @code.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @code.text %>
</p>

<%= link_to '<- Back', codes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cloudish</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page, local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :index %>
    <%= form.text_field :index, id: :page_index %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pages</h1>

<table>
  <thead>
    <tr>
      <th>Index</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.index %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/indexShow.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Privacy Policy</strong>

</p>

app/views/pages/indexToS.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Terms of Service</strong>

</p>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Index:</strong>
  <%= @page.index %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/search/search.html.erb
<h1>Code Search</h1>

<%= form_for search_path, method: :get do |f| %>
  <p>
    <%= f.label "Enter an ICD-10 code or description.." %>
    <%= text_field_tag :q, params[:q] %>
    <%= submit_tag "Search", name: nil %>
  </p>
<% end %>

<ul>
  <% @codes.records.each do |code| %>
    <li>
      <h3>
        <%= link_to code.desc, controller: "codes", action: "show", id: code.code_id%>
      </h3>
    </li>
  <% end %>
</ul>